/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./app/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        // Base colors
        background: 'var(--background)',
        foreground: 'var(--foreground)',
        border: 'var(--color-border)',
        input: 'var(--color-input)',
        ring: 'var(--color-ring)',

        // Neutral colors
        neutral: {
          25: 'var(--color-neutral-25)',
          50: 'var(--color-neutral-50)',
          100: 'var(--color-neutral-100)',
          200: 'var(--color-neutral-200)',
          300: 'var(--color-neutral-300)',
          400: 'var(--color-neutral-400)',
          500: 'var(--color-neutral-500)',
          600: 'var(--color-neutral-600)',
          700: 'var(--color-neutral-700)',
          800: 'var(--color-neutral-800)',
          900: 'var(--color-neutral-900)',
          950: 'var(--color-neutral-950)',
          // Alpha variants
          a25: 'var(--color-neutral-a25)',
          a50: 'var(--color-neutral-a50)',
          a100: 'var(--color-neutral-a100)',
          a200: 'var(--color-neutral-a200)',
          a300: 'var(--color-neutral-a300)',
          a400: 'var(--color-neutral-a400)',
          a500: 'var(--color-neutral-a500)',
          a600: 'var(--color-neutral-a600)',
          a700: 'var(--color-neutral-a700)',
          a800: 'var(--color-neutral-a800)',
          a900: 'var(--color-neutral-a900)',
          a950: 'var(--color-neutral-a950)',
        },

        // Info colors
        info: {
          25: 'var(--color-info-25)',
          50: 'var(--color-info-50)',
          100: 'var(--color-info-100)',
          200: 'var(--color-info-200)',
          300: 'var(--color-info-300)',
          400: 'var(--color-info-400)',
          500: 'var(--color-info-500)',
          600: 'var(--color-info-600)',
          700: 'var(--color-info-700)',
          800: 'var(--color-info-800)',
          900: 'var(--color-info-900)',
          950: 'var(--color-info-950)',
          // Alpha variants
          a25: 'var(--color-info-a25)',
          a50: 'var(--color-info-a50)',
          a100: 'var(--color-info-a100)',
          a200: 'var(--color-info-a200)',
          a300: 'var(--color-info-a300)',
          a400: 'var(--color-info-a400)',
          a500: 'var(--color-info-a500)',
          a600: 'var(--color-info-a600)',
          a700: 'var(--color-info-a700)',
          a800: 'var(--color-info-a800)',
          a900: 'var(--color-info-a900)',
          a950: 'var(--color-info-a950)',
        },

        // Success colors
        success: {
          25: 'var(--color-success-25)',
          50: 'var(--color-success-50)',
          100: 'var(--color-success-100)',
          200: 'var(--color-success-200)',
          300: 'var(--color-success-300)',
          400: 'var(--color-success-400)',
          500: 'var(--color-success-500)',
          600: 'var(--color-success-600)',
          700: 'var(--color-success-700)',
          800: 'var(--color-success-800)',
          900: 'var(--color-success-900)',
          950: 'var(--color-success-950)',
          // Alpha variants
          a25: 'var(--color-success-a25)',
          a50: 'var(--color-success-a50)',
          a100: 'var(--color-success-a100)',
          a200: 'var(--color-success-a200)',
          a300: 'var(--color-success-a300)',
          a400: 'var(--color-success-a400)',
          a500: 'var(--color-success-a500)',
          a600: 'var(--color-success-a600)',
          a700: 'var(--color-success-a700)',
          a800: 'var(--color-success-a800)',
          a900: 'var(--color-success-a900)',
          a950: 'var(--color-success-a950)',
        },

        // Warning colors
        warning: {
          25: 'var(--color-warning-25)',
          50: 'var(--color-warning-50)',
          100: 'var(--color-warning-100)',
          200: 'var(--color-warning-200)',
          300: 'var(--color-warning-300)',
          400: 'var(--color-warning-400)',
          500: 'var(--color-warning-500)',
          600: 'var(--color-warning-600)',
          700: 'var(--color-warning-700)',
          800: 'var(--color-warning-800)',
          900: 'var(--color-warning-900)',
          950: 'var(--color-warning-950)',
          // Alpha variants
          a25: 'var(--color-warning-a25)',
          a50: 'var(--color-warning-a50)',
          a100: 'var(--color-warning-a100)',
          a200: 'var(--color-warning-a200)',
          a300: 'var(--color-warning-a300)',
          a400: 'var(--color-warning-a400)',
          a500: 'var(--color-warning-a500)',
          a600: 'var(--color-warning-a600)',
          a700: 'var(--color-warning-a700)',
          a800: 'var(--color-warning-a800)',
          a900: 'var(--color-warning-a900)',
          a950: 'var(--color-warning-a950)',
        },

        // Danger colors
        danger: {
          25: 'var(--color-danger-25)',
          50: 'var(--color-danger-50)',
          100: 'var(--color-danger-100)',
          200: 'var(--color-danger-200)',
          300: 'var(--color-danger-300)',
          400: 'var(--color-danger-400)',
          500: 'var(--color-danger-500)',
          600: 'var(--color-danger-600)',
          700: 'var(--color-danger-700)',
          800: 'var(--color-danger-800)',
          900: 'var(--color-danger-900)',
          950: 'var(--color-danger-950)',
          // Alpha variants
          a25: 'var(--color-danger-a25)',
          a50: 'var(--color-danger-a50)',
          a100: 'var(--color-danger-a100)',
          a200: 'var(--color-danger-a200)',
          a300: 'var(--color-danger-a300)',
          a400: 'var(--color-danger-a400)',
          a500: 'var(--color-danger-a500)',
          a600: 'var(--color-danger-a600)',
          a700: 'var(--color-danger-a700)',
          a800: 'var(--color-danger-a800)',
          a900: 'var(--color-danger-a900)',
          a950: 'var(--color-danger-a950)',
        },

        // Accent colors
        accent: {
          25: 'var(--color-accent-25)',
          50: 'var(--color-accent-50)',
          100: 'var(--color-accent-100)',
          200: 'var(--color-accent-200)',
          300: 'var(--color-accent-300)',
          400: 'var(--color-accent-400)',
          500: 'var(--color-accent-500)',
          600: 'var(--color-accent-600)',
          700: 'var(--color-accent-700)',
          800: 'var(--color-accent-800)',
          900: 'var(--color-accent-900)',
          950: 'var(--color-accent-950)',
          // Alpha variants
          a25: 'var(--color-accent-a25)',
          a50: 'var(--color-accent-a50)',
          a100: 'var(--color-accent-a100)',
          a200: 'var(--color-accent-a200)',
          a300: 'var(--color-accent-a300)',
          a400: 'var(--color-accent-a400)',
          a500: 'var(--color-accent-a500)',
          a600: 'var(--color-accent-a600)',
          a700: 'var(--color-accent-a700)',
          a800: 'var(--color-accent-a800)',
          a900: 'var(--color-accent-a900)',
          a950: 'var(--color-accent-a950)',

          DEFAULT: 'var(--color-neutral-100)',
          hover: 'var(--color-neutral-200)',
          active: 'var(--color-neutral-300)',
          foreground: 'var(--color-foreground)',
        },

        // Primary/Secondary/Destructive
        primary: {
          DEFAULT: 'var(--color-primary)',
          foreground: 'var(--color-primary-foreground)',
          hover: 'var(--color-primary-hover)',
          active: 'var(--color-primary-active)',
        },
        secondary: {
          DEFAULT: 'var(--color-secondary)',
          foreground: 'var(--color-secondary-foreground)',
          hover: 'var(--color-secondary-hover)',
          active: 'var(--color-secondary-active)',
        },
        destructive: {
          DEFAULT: 'var(--color-destructive)',
          foreground: 'var(--color-destructive-foreground)',
          hover: 'var(--color-destructive-hover)',
          active: 'var(--color-destructive-active)',
        },

        // UI specific colors
        muted: {
          DEFAULT: 'var(--color-muted)',
          foreground: 'var(--color-muted-foreground)',
        },
        popover: {
          DEFAULT: 'var(--color-popover)',
          foreground: 'var(--color-popover-foreground)',
        },
        card: {
          DEFAULT: 'var(--color-card)',
          foreground: 'var(--color-card-foreground)',
        },

        chart: {
          1: 'var(--color-chart-1)',
          2: 'var(--color-chart-2)',
          3: 'var(--color-chart-3)',
          4: 'var(--color-chart-4)',
          5: 'var(--color-chart-5)',
        },

        sidebar: {
          DEFAULT: 'var(--color-background)',
          foreground: 'var(--color-foreground)',
          primary: 'var(--color-primary)',
          primaryForeground: 'var(--color-primary-foreground)',
          accent: 'var(--color-accent)',
          accentForeground: 'var(--color-accent-foreground)',
          border: 'var(--color-border)',
          ring: 'var(--color-ring)',
        },
      },
      borderRadius: {
        xs: 'var(--radius-xs)',
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
      },
      keyframes: {
        'accordion-down': {
          from: { height: 0 },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: 0 },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      },
    },
  },
  plugins: [require('@tailwindcss/typography'), require('tailwindcss-animate')],
}
